set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property PACKAGE_PIN B11 [get_ports VGA_HS]
set_property PACKAGE_PIN B12 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]



set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]




set_property PACKAGE_PIN P17 [get_ports {action[3]}]
set_property PACKAGE_PIN P18 [get_ports {action[2]}]
set_property PACKAGE_PIN M17 [get_ports {action[1]}]
set_property PACKAGE_PIN M18 [get_ports {action[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {action[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {action[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {action[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {action[0]}]


set_input_delay -clock [get_clocks *] 0.000 [get_ports reset]
set_output_delay -clock [get_clocks clk_pin] 0.000 [get_ports -filter {NAME=~ "*" &&DIRECTION =="OUT"}]
set_input_delay -clock [get_clocks clk_pin] 0.000 [get_ports reset]
create_clock -period 30.000 -name clk_pin -waveform {0.000 15.000} [get_ports clk_in]
