######################################################################
#
# File name : tb_wave.do
# Created on: Fri Jun 15 13:04:19 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
