######################################################################
#
# File name : sccomp_dataflow_wave.do
# Created on: Wed Jul 25 15:59:06 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
