######################################################################
#
# File name : sccomp_dataflow_compile.do
# Created on: Wed Jul 25 15:58:50 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib
vlib msim/xpm
vlib msim/dist_mem_gen_v8_0_10

vmap xil_defaultlib msim/xil_defaultlib
vmap xpm msim/xpm
vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

vlog -64 -incr -sv -work xil_defaultlib  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

vcom -64 -93 -work xpm  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work xil_defaultlib  \
"../../../mips54.srcs/sources_1/new/MULTU.v" \
"../../../mips54.srcs/sources_1/new/MULT.v" \
"../../../mips54.srcs/sources_1/new/fuck_regfile.v" \
"../../../mips54.srcs/sources_1/new/DIVU.v" \
"../../../mips54.srcs/sources_1/new/DIV.v" \

vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../mips54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../mips54.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../mips54.srcs/sources_1/new/MDU.v" \
"../../../mips54.srcs/sources_1/new/cp0.v" \
"../../../mips54.srcs/sources_1/new/controlunit.v" \
"../../../mips54.srcs/sources_1/new/ALU.V" \
"../../../mips54.srcs/sources_1/new/pcreg.v" \
"../../../mips54.srcs/sources_1/new/ram.v" \
"../../../mips54.srcs/sources_1/new/top_id.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

