# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/youyaoyin/mips54/mips54.cache/wt [current_project]
set_property parent.project_path C:/Users/youyaoyin/mips54/mips54.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files d:/下载/CPU测试COE文件/mips_54_mars_simulate_student_ForWeb.coe
add_files {{C:/Users/youyaoyin/OneDrive/作业/计算机组成原理作业/Mars4_5 导出十六进制文件及结果比对说明/123.coe}}
add_files {{C:/Users/youyaoyin/OneDrive/作业/计算机组成原理作业/Mars4_5 导出十六进制文件及结果比对说明/test.coe}}
add_files C:/Users/youyaoyin/Pictures/game/sea.coe
add_files C:/Users/youyaoyin/Pictures/game/boatleft.coe
add_files {{C:/Users/youyaoyin/OneDrive/作业/计算机组成原理作业/Mars4_5 导出十六进制文件及结果比对说明/warship.coe}}
add_files {{C:/Users/youyaoyin/OneDrive/作业/计算机组成原理作业/Mars4_5 导出十六进制文件及结果比对说明/final.coe}}
add_files -quiet c:/Users/youyaoyin/mips54/mips54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/mips54/mips54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
add_files -quiet c:/Users/youyaoyin/mips54/mips54.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/mips54/mips54.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet c:/Users/youyaoyin/mips54/mips54.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/mips54/mips54.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/MULTU.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/MULT.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/fuck_regfile.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/DIVU.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/DIV.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/vga_signal.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/MDU.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/cp0.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/controlunit.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/ALU.V
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/pcreg.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/ram.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/warship.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/top_id.v
  C:/Users/youyaoyin/mips54/mips54.srcs/sources_1/new/tb2.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/youyaoyin/mips54/mips54.srcs/constrs_1/new/vga_test.xdc
set_property used_in_implementation false [get_files C:/Users/youyaoyin/mips54/mips54.srcs/constrs_1/new/vga_test.xdc]


synth_design -top tb2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef tb2.dcp

catch { report_utilization -file tb2_utilization_synth.rpt -pb tb2_utilization_synth.pb }
